services:
  api:
    build:
      context: .              # Use current backend directory as context
      dockerfile: Dockerfile  # Our Dockerfile is in backend/
    volumes:
      - .:/var/www            # Mount backend/ into container
    networks:
      - app-network
    depends_on:
      - db
      - searcher

  controller:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - app-network

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  searcher:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  es_data:
